### ISSUE TITLE
Post Messages/Announcements Via Bot

### ISSUE THREAD

**Issue by JohnnyLeibniz** [Project-Kindling/Discord-Bot#1]
**DESCRIPTION**
For this basic feature, the idea would be that a user can message the bot in _in a channel on a given server_ in order to make the bot re-post whatever their message may be, with appropriate formatting, into a different channel of their choice.

The command would take in the channel the message should be posted in as well as the actual message content.

**USAGE**
`%announce @CHANNEL_NAME ANNOUNCEMENT_CONTENT`

**Comment by maralihart** [comment]
```
if %announce is sent:
look for what's mentioned in the message
get the channel object based off the mention in the message
await channel.send(announcement_content)
```

**Comment by abrarahsan16** [comment]
Improvement: 
Make the bot only accept %announce commands from a specific channel. This will force the user to only write announcements where it needs to be, and creates a "log" of who wrote the announce command.

**Comment by abrarahsan16** [comment]
Announcements work now
