### ISSUE TITLE
Get ANONYMOUS Feedback from Server Members

### ISSUE THREAD

**Issue by JohnnyLeibniz** [Project-Kindling/Discord-Bot#2]
**DESCRIPTION**
For this basic feature, the idea would be that a user can message the bot _privately / in DM's_ and use the command to give feedback on the server itself. The bot would message this info to a channel without stating who sent it the info, instead simply noting it as 'anonymous feedback.'

That feedback should then be send to a _specific channel in the Project Kindling public server._ This channel can just be called 'feedback' for the sake of clarity, and will be a private channel only visible to those with the Project Kindling Team role.

Bonus points if each message from the bot looks pretty (embed)!

**USAGE**
`%feedback FEEDBACK_INFORMATION`

**Comment by abrarahsan16** [comment]
Messaging the bot allows for feedback
