### ISSUE TITLE
Create Simple Poll With Vote Counter

### ISSUE THREAD

**Issue by JohnnyLeibniz** [Project-Kindling/Discord-Bot#3]
**Is your feature request related to a problem? Please describe.**
Being able to easily create a poll without requiring a separate bot. Also to see how many votes a poll receives.

**Describe the solution you'd like**
Create a simple command that allows a user to create a poll in the channel, where other server members vote via the automatically generated reactions. Should preferably be an embed to make it p r e t t y. Features I'd like in each poll are:

- Title of Poll
- All options (generated automatically as A - L, ie up to 12 poll options at once)
- Total Votes counter
- Automatically generated reactions so people can vote easily.

Example usage: `%poll What is your favorite color? "Blue" "Red" "Yellow"`

**Describe alternatives you've considered**
Using a separate poll bot is also fine, but it would be cool to do this via the Kindling Bot, especially to customize it to our preferences over time.

**Do you have examples of other implementations?**
Below is how I imagine it looking for now. Note that the 'poll with be open until...' portion is not necessary.
![image](https://user-images.githubusercontent.com/30630302/123305413-12f0ad80-d4ee-11eb-82dd-7ddd4de9d18b.png)

**Comment by abrarahsan16** [comment]
Polls are generated, but the Total Votes count does not increase. Needs further work

**Comment by iktefish** [comment]
Polling feature's ready and functional. Finalized with #14

**Comment by abrarahsan16** [comment]
%poll feature is not functional

**Comment by abrarahsan16** [comment]
Opening new ticket
